name = "Musica"
uuid = "d3d182ee-e566-4962-9279-3a9916be1802"
authors = ["ACOM MUSICA Developers <musica-support@ucar.edu>"]
version = "0.14.4"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CxxWrap = "^0.16"
Libdl = "1.10, 1.11"
julia = "1.10 - 1.11"
