name: musica-env
channels:
  - conda-forge
dependencies:
  - blas
  - cmake
  - gcc
  - gxx
  - gfortran
  - git
  - hdf5
  - lapack
  - libcurl
  - make
  - netcdf-fortran
  - openssl
  - pip
  - pkg-config
  - python>=3.9
  - zlib
  - pip:
    - ussa1976>=v0.3.4
    - ../.[tutorial]
