name: Format Code with Clang-Format, Prettier, autopep8, and JuliaFormatter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Run Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install clang-format && clang-format --version

      - name: Check out code, run clang format, push changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'

      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --aggressive --aggressive --max-line-length 120 .

      - name: Run clang-format
        run: |
          find include -type f \( -name '*.hpp' -or -name '*.h' \) -exec clang-format -i --style=file --verbose {} +
          find src -type f \( -name '*.cpp' -or -name '*.c' \) -exec clang-format -i --style=file --verbose {} +
          find python -type f \( -name '*.cpp' -or -name '*.c' -or -name '*.hpp' -or -name '*.h' \) -exec clang-format -i --style=file --verbose {} +
          find javascript -type f \( -name '*.cpp' -or -name '*.c' -or -name '*.hpp' -or -name '*.h' \) -exec clang-format -i --style=file --verbose {} +
          find julia -type f \( -name '*.cpp' -or -name '*.c' -or -name '*.hpp' -or -name '*.h' \) -exec clang-format -i --style=file --verbose {} +

      - name: Format JavaScript
        run: npm run format:js

      - name: Format Julia
        run: julia -e 'using JuliaFormatter; format("julia")'

      - name: Check for changes
        id: check-changes
        run: git diff --exit-code
        continue-on-error: true

      - name: Commit and push changes
        # a failue of this step means changes were detected
        if: steps.check-changes.outcome != 'success'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Auto-format code using Clang-Format, Prettier, autopep8, and JuliaFormatter" || echo "No changes to commit"

      - name: Push changes to main-formatting branch
        if: steps.check-changes.outcome != 'success'
        run: git push origin HEAD:main-formatting

      - name: Create Pull Request
        if: steps.check-changes.outcome != 'success'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-format code using Clang-Format, Prettier, autopep8, and JuliaFormatter"
          title: "Auto-format code changes"
          body: "This is an automated pull request to apply code formatting using Clang-Format, Prettier, autopep8, and JuliaFormatter."
          branch: main-formatting