name: Javascript Tests

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  wasm:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: ["v22", "v24"]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up EMSDK
        id: emsdk
        uses: ./.github/emsdk_steps

      - name: Install dependencies
        run: npm ci

      - name: Build wasm
        run: |
          source ${{ steps.emsdk.outputs.emsdk-env-file }}
          npm run build

      - name: Test
        run: npm test

  publish:
    name: Build WASM for publishing
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Set up EMSDK
        id: emsdk
        uses: ./.github/emsdk_steps

      - name: Install dependencies
        run: npm ci

      - name: Build wasm
        run: |
          source ${{ steps.emsdk.outputs.emsdk-env-file }}
          npm --version
          node --version
          npm run build

      - name: Test
        run: npm run test
      
      - name: Copy javascript readme
        run: cp javascript/README.md README.md # npm uses the root README for the package page
      
      - name: List config
        run: |
          npm --version
          node --version
          npm config list -l

      - name: Publish to npm
        run: NODE_AUTH_TOKEN="" npm publish --access public --provenance
